import Provider from '@/context/Provider';
import './globals.scss';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Footer, Header } from '@/components/exportComponents';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className}`}>
				<Provider>
					<Header />
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
